import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HomeContent from "./homeContent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Jump Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ paddingBottom: 16 }} className={styles.description}>
          <p>
            Your&nbsp;
            <code className={styles.code}>Beer </code>
            Manager
          </p>
          <div>
            <a
              href="https://github.com/HugoChollet"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Hugo
            </a>
          </div>
        </div>

        <HomeContent />
      </main>
    </>
  );
}
